# Test GET / on Render
GET https://cse341-webbackend.onrender.com/

###

# Test GET /contacts (all contacts) on Render
GET https://cse341-webbackend.onrender.com/contacts

###

# Test GET /contacts?id=<id> (single contact) on Render
GET https://cse341-webbackend.onrender.com/contacts?id=680474c38ed82fec5150f907

###

# Test POST /contacts on Render
POST https://cse341-webbackend.onrender.com/contacts
Content-Type: application/json

{"firstName":"Carol","lastName":"Jones","email":"carol@example.com"}