# LOCALHOST

### Get localhost
GET http://localhost:3000/

### Get all contacts
GET http://localhost:3000/contacts

### Get contact by id
GET http://localhost:3000/contacts/681fa46d5e41dc07dd81635f HTTP/1.1

### Create contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Emma",
  "lastName": "Davis",
  "email": "emma.davis@example.com",
  "favoriteColor": "Purple",
  "birthday": "1990-06-25"
}

### PUT contact
PUT http://localhost:3000/contacts/681f95c0f744b3159bf98fbe HTTP/1.1
content-type: application/json

{
  "firstName": "Emma",
  "lastName": "Davis",
  "email": "emma.davis@example.com",
  "favoriteColor": "Pink",
  "birthday": "1990-06-25"
}

### DELETE contact
DELETE http://localhost:3000/contacts/681fa46d5e41dc07dd81635f HTTP/1.1

### Get root endpoint
GET https://cse341-webbackend.onrender.com/

# PRODUCTION Deploy
### Get all contacts
GET https://cse341-webbackend.onrender.com/contacts

### Get contact by id
GET https://cse341-webbackend.onrender.com/contacts/68290d7d80ae12a73046c829 HTTP/1.1

### Create contact
POST https://cse341-webbackend.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Clara",
  "lastName": "Williams",
  "email": "clara.williams@example.com",
  "favoriteColor": "Yellow",
  "birthday": "1988-11-30"
}

### PUT contact
PUT https://cse341-webbackend.onrender.com/contacts/681f95c0f744b3159bf98fbe HTTP/1.1
content-type: application/json

{
    "firstName": "Carol",
    "lastName": "Smith",
    "email": "carol.smith@example.com",
    "favoriteColor": "Turquoise",
    "birthday": "1990-05-15"
}

### DELETE contact
DELETE https://cse341-webbackend.onrender.com/contacts/681f95c0f744b3159bf98fbe HTTP/1.1